apiVersion: v1
kind: Secret
metadata:
  name: login
  namespace: tt
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ3d3cuZmVkZW1vLmNuOjgwODIiOiB7CgkJCSJhdXRoIjogImVtUjZkM042T2tCWGMzcDZaSG94TWpNPSIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTkuMDMuMCAobGludXgpIgoJfQp9